<a href="https://colab.research.google.com/github/GudaObulaReddy/ML-and-Datascince/blob/main/Save_and_load_trained_model_using_pickle_and_sklearn_joblib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
#here  i am using linear regression because as area increases price increases

In [4]:
df=pd.read_csv("/content/drive/MyDrive/homeprices.csv")
df.head(5)


area  bedrooms   age   price
0   548       5.0  24.0  208500
1   460       4.0  26.0  181500
2   608       5.0  57.0  223500
3   642       4.0  54.0  140000
4   836       2.0   NaN  250000

In [5]:
df.isnull().sum()

area        0
bedrooms    4
age         4
price       0
dtype: int64

In [6]:
# Handling NAN values
# Here age and bedrooms replaced with median


In [7]:
df["bedrooms"].median()

3.0

In [8]:
df["age"].median()

33.0

In [9]:
df.bedrooms=df["bedrooms"].fillna(df["bedrooms"].median())

In [10]:
df.age=df["age"].fillna(df["age"].median())

In [11]:
df.isna().sum()

area        0
bedrooms    0
age         0
price       0
dtype: int64

In [12]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','age','bedrooms']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [13]:
reg.coef_

array([232.13084309, 101.84289625, 756.89700084])

In [14]:
reg.intercept_

65571.59038490478

In [15]:
reg.predict([[500,3,40]])

array([212218.42065087])

price=coef1$*$area+coef2$*$age+coef3$*$bedrooms+intercept

In [16]:
232.13084309*500+101.84289625*3+756.89700084*40+65571.59038490478

212218.42065225478

In [17]:
testdata=pd.read_csv("/content/drive/MyDrive/homepricetestdata.csv")

In [18]:
p=reg.predict(testdata)

In [19]:
testdata['price']=p

In [20]:
testdata.head()

area  bedrooms  age          price
0   548         1   19  207262.178309
1   460         1   36  199701.913132
2   608         2   32  231131.532801
3   642         2   54  255675.715485
4   836         2   35  286328.056028

In [21]:
import pickle

In [23]:
with open('model_pickle','wb') as f:
     pickle.dump(reg,f)

In [24]:
with open('model_pickle','rb') as f:
  mp=pickle.load(f)
  

In [27]:
mp.predict([[500,3,40]])

array([212218.42065087])

In [28]:
from sklearn.externals import joblib

/usr/local/lib/python3.7/dist-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


In [29]:
joblib.dump(reg,'model_joblib')

['model_joblib']

In [30]:
mj=joblib.load('model_joblib')

In [31]:
mj.predict([[500,3,40]])

array([212218.42065087])

In [32]:
mj.coef_

array([232.13084309, 101.84289625, 756.89700084])

In [33]:
mj.intercept_

65571.59038490478